name: Update Leaderboard on analysis_results.json Change

on:
  push:
    paths:
      - 'analysis_results.json'
  workflow_dispatch:  

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run leaderboard update script
        run: python leaderboard/generate.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add leaderboard/site/index.html
          git commit -m "Update leaderboard based on latest analysis_results.json" || echo "No changes to commit"
          git push